const INITILIZE_LOCATIONS = "INITILIZE_LOCATIONS";
const LOGIN_USER = "LOGIN_USER";
const LOGOUT_USER = "LOGOUT_USER";
const ALL_USERS = "ALL_USERS";

export { INITILIZE_LOCATIONS, LOGIN_USER, LOGOUT_USER, ALL_USERS };
