const CREATE_LOCATION = "CREATE_LOCATION";
const CREATE_BLOCK = "CREATE_BLOCK";
const INITILIZE_LOCATIONS = "INITILIZE_LOCATIONS";
const LOGIN_USER = "LOGIN_USER";

export { CREATE_LOCATION, CREATE_BLOCK, INITILIZE_LOCATIONS, LOGIN_USER };
