const DASHBOARD = "DASHBOARD";
const LOCATION = "LOCATION";
const BILLING = "BILLING";
const CREATE_LOCATION = "CREATE_LOCATION";
const CREATE_USER = "CREATE_USER";
const VIEW_TASKLOG = "VIEW_TASKLOG";
const CREATE_POST = "CREATE_POST";
const PROFILE = "PROFILE";
const GENERATE_REPORT = "GENERATE_REPORT";

export {
  DASHBOARD,
  LOCATION,
  BILLING,
  CREATE_LOCATION,
  CREATE_USER,
  VIEW_TASKLOG,
  CREATE_POST,
  PROFILE,
  GENERATE_REPORT,
};
