const DASHBOARD = "DASHBOARD";
const LOCATION = "LOCATION";
const BILLING = "BILLING";
const CREATE_LOCATION = "CREATE_LOCATION";
const CREATE_USER = "CREATE_USER";

export { DASHBOARD, LOCATION, BILLING, CREATE_LOCATION, CREATE_USER };
