const DASHBOARD = "DASHBOARD";
const LOCATION = "LOCATION";
const BILLING = "BILLING";
const CREATE_LOCATION = "CREATE_LOCATION";
const CREATE_USER = "CREATE_USER";
const VIEW_TASKLOG = "VIEW_TASKLOG";

export { DASHBOARD, LOCATION, BILLING, CREATE_LOCATION, CREATE_USER, VIEW_TASKLOG };
